# TINY SMALL MEDIUM BIG INTs
INT
INT(3)
INT AUTO_INCREMENT PRIMARY KEY
INT UNSIGNED
INT ZEROFILL # Pads with Zeroes

DECIMAL(max_digits,float_digits)
FLOAT
DOUBLE

CHAR # Fixed Length - always that num
CHAR(3)

VARCHAR # Variable Length - Could be UP to N chars long
VARCHAR(255)

# DATES
DATE
TIME
DATETIME
TIMESTAMP DEFAULT CURRENT_TIMESTAMP
TIMESTAMP DEFAULT CURRENT_TIMESTAMP   ON UPDATE CURRENT_TIMESTAMP